### PR TITLE
Add Assembly metrics tracker

### PR DESCRIPTION
**Pull request by whatupdave**
This collects metrics and adds a metrics screen on Assembly so everyone can see Signup sumo numbers.

ASMLYTICS_APP_ID will need to be set based on the code: https://assembly.com/signupsumo/metrics

### CODE REVIEW

**Comment by barberj** [comment]
@whatupdave i'm not prevey to the code. I can merge and deploy, but need to be given the code for the env

**Comment by whatupdave** [comment]
Oops, try  https://assembly.com/signupsumo/metrics/snippet

**Comment by barberj** [comment]
added code to heroku env settings

**Comment by barberj** [comment]
@whatupdave how long does it take for the metrics to populate? I've logged in post deploy and still just seeing 

screen shot 2015-03-12 at 9 18 08 pm

**Comment by whatupdave** [comment]
It actually takes a few days before it has enough to satisfy it

**Comment by barberj** [comment]
10-4

**Pull request merged**
