### PR TITLE
Adds postgres version to fig.yml

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by kenrick** [comment]
:+1:

**Comment by cmckni3** [comment]
@kenrick Glad you like it. Should make pulling the postgres image so much faster since it doesn't pull all of the images.

**Comment by kenrick** [comment]
yeah its annoying imagine pulling all the versions of ruby on the docker registry

**Comment by vanstee** [comment]
Oh nice yeah this was tripping me up, since some of the versions would randomly fail during lookup.

**Pull request merged**
