### PR TITLE
Fix mailer

### PR DESCRIPTION
**Pull request by bshyong**

### CODE REVIEW

**Comment by bshyong** [comment]
@vanstee I think this should work?  image urls in the email are generated correctly (including the digest).

**Comment by vanstee** [comment]
Man that's nuts. Could you just remove those `puts` calls real quick. Looks like a good but gnarly fix. Thanks man.

**Comment by bshyong** [comment]
working on it; might have a cleaner fix if you are down with using premailer instead of roadie?
https://github.com/fphilipe/premailer-rails

**Comment by vanstee** [comment]
Sure that's fine.

**Comment by bshyong** [comment]
@vanstee the mailer looks good for me on local now (got images to show up)

**Comment by vanstee** [comment]
Should I go ahead and merge and then just clean things up later?

**Comment by bshyong** [comment]
yep; only cleanup we might need is styles—for some reason our elements were inheriting a transparent background + black text !important so I just overrode manually for now.  Also background works on `tr` but not on `td`..super odd.

Not sure of a good way to test in production, but all of the asset_host stuff works locally

**Comment by vanstee** [comment]
Cool I'll merge this. Shipping it is the best way to try it in production for now.

**Pull request merged**
